// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.23.0
// 	protoc        v3.11.4
// source: meteorite-landing-service.proto

package api

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type GeoLocation struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type        string    `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Coordinates []float64 `protobuf:"fixed64,2,rep,packed,name=coordinates,proto3" json:"coordinates,omitempty"`
}

func (x *GeoLocation) Reset() {
	*x = GeoLocation{}
	if protoimpl.UnsafeEnabled {
		mi := &file_meteorite_landing_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GeoLocation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GeoLocation) ProtoMessage() {}

func (x *GeoLocation) ProtoReflect() protoreflect.Message {
	mi := &file_meteorite_landing_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GeoLocation.ProtoReflect.Descriptor instead.
func (*GeoLocation) Descriptor() ([]byte, []int) {
	return file_meteorite_landing_service_proto_rawDescGZIP(), []int{0}
}

func (x *GeoLocation) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *GeoLocation) GetCoordinates() []float64 {
	if x != nil {
		return x.Coordinates
	}
	return nil
}

type MeteoriteLanding struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          string       `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name        string       `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Fall        string       `protobuf:"bytes,3,opt,name=fall,proto3" json:"fall,omitempty"`
	Geolocation *GeoLocation `protobuf:"bytes,4,opt,name=geolocation,proto3" json:"geolocation,omitempty"`
	Mass        string       `protobuf:"bytes,5,opt,name=mass,proto3" json:"mass,omitempty"`
	Nametype    string       `protobuf:"bytes,6,opt,name=nametype,proto3" json:"nametype,omitempty"`
	Recclass    string       `protobuf:"bytes,7,opt,name=recclass,proto3" json:"recclass,omitempty"`
	Reclat      string       `protobuf:"bytes,8,opt,name=reclat,proto3" json:"reclat,omitempty"`
	Reclong     string       `protobuf:"bytes,9,opt,name=reclong,proto3" json:"reclong,omitempty"`
	Year        string       `protobuf:"bytes,10,opt,name=year,proto3" json:"year,omitempty"`
}

func (x *MeteoriteLanding) Reset() {
	*x = MeteoriteLanding{}
	if protoimpl.UnsafeEnabled {
		mi := &file_meteorite_landing_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MeteoriteLanding) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MeteoriteLanding) ProtoMessage() {}

func (x *MeteoriteLanding) ProtoReflect() protoreflect.Message {
	mi := &file_meteorite_landing_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MeteoriteLanding.ProtoReflect.Descriptor instead.
func (*MeteoriteLanding) Descriptor() ([]byte, []int) {
	return file_meteorite_landing_service_proto_rawDescGZIP(), []int{1}
}

func (x *MeteoriteLanding) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *MeteoriteLanding) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MeteoriteLanding) GetFall() string {
	if x != nil {
		return x.Fall
	}
	return ""
}

func (x *MeteoriteLanding) GetGeolocation() *GeoLocation {
	if x != nil {
		return x.Geolocation
	}
	return nil
}

func (x *MeteoriteLanding) GetMass() string {
	if x != nil {
		return x.Mass
	}
	return ""
}

func (x *MeteoriteLanding) GetNametype() string {
	if x != nil {
		return x.Nametype
	}
	return ""
}

func (x *MeteoriteLanding) GetRecclass() string {
	if x != nil {
		return x.Recclass
	}
	return ""
}

func (x *MeteoriteLanding) GetReclat() string {
	if x != nil {
		return x.Reclat
	}
	return ""
}

func (x *MeteoriteLanding) GetReclong() string {
	if x != nil {
		return x.Reclong
	}
	return ""
}

func (x *MeteoriteLanding) GetYear() string {
	if x != nil {
		return x.Year
	}
	return ""
}

type MeteoriteLandingList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MeteoriteLanding []*MeteoriteLanding `protobuf:"bytes,1,rep,name=meteoriteLanding,proto3" json:"meteoriteLanding,omitempty"`
}

func (x *MeteoriteLandingList) Reset() {
	*x = MeteoriteLandingList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_meteorite_landing_service_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MeteoriteLandingList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MeteoriteLandingList) ProtoMessage() {}

func (x *MeteoriteLandingList) ProtoReflect() protoreflect.Message {
	mi := &file_meteorite_landing_service_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MeteoriteLandingList.ProtoReflect.Descriptor instead.
func (*MeteoriteLandingList) Descriptor() ([]byte, []int) {
	return file_meteorite_landing_service_proto_rawDescGZIP(), []int{2}
}

func (x *MeteoriteLandingList) GetMeteoriteLanding() []*MeteoriteLanding {
	if x != nil {
		return x.MeteoriteLanding
	}
	return nil
}

var File_meteorite_landing_service_proto protoreflect.FileDescriptor

var file_meteorite_landing_service_proto_rawDesc = []byte{
	0x0a, 0x1f, 0x6d, 0x65, 0x74, 0x65, 0x6f, 0x72, 0x69, 0x74, 0x65, 0x2d, 0x6c, 0x61, 0x6e, 0x64,
	0x69, 0x6e, 0x67, 0x2d, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x09, 0x6d, 0x65, 0x74, 0x65, 0x6f, 0x72, 0x69, 0x74, 0x65, 0x1a, 0x1b, 0x67, 0x6f,
	0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x65, 0x6d,
	0x70, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x43, 0x0a, 0x0b, 0x47, 0x65, 0x6f,
	0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x20, 0x0a, 0x0b,
	0x63, 0x6f, 0x6f, 0x72, 0x64, 0x69, 0x6e, 0x61, 0x74, 0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28,
	0x01, 0x52, 0x0b, 0x63, 0x6f, 0x6f, 0x72, 0x64, 0x69, 0x6e, 0x61, 0x74, 0x65, 0x73, 0x22, 0x96,
	0x02, 0x0a, 0x10, 0x4d, 0x65, 0x74, 0x65, 0x6f, 0x72, 0x69, 0x74, 0x65, 0x4c, 0x61, 0x6e, 0x64,
	0x69, 0x6e, 0x67, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x66, 0x61, 0x6c, 0x6c, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x66, 0x61, 0x6c, 0x6c, 0x12, 0x38, 0x0a, 0x0b, 0x67,
	0x65, 0x6f, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x16, 0x2e, 0x6d, 0x65, 0x74, 0x65, 0x6f, 0x72, 0x69, 0x74, 0x65, 0x2e, 0x47, 0x65, 0x6f,
	0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x0b, 0x67, 0x65, 0x6f, 0x6c, 0x6f, 0x63,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x6d, 0x61, 0x73, 0x73, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x6d, 0x61, 0x73, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x6e, 0x61, 0x6d,
	0x65, 0x74, 0x79, 0x70, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6e, 0x61, 0x6d,
	0x65, 0x74, 0x79, 0x70, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x72, 0x65, 0x63, 0x63, 0x6c, 0x61, 0x73,
	0x73, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x72, 0x65, 0x63, 0x63, 0x6c, 0x61, 0x73,
	0x73, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x63, 0x6c, 0x61, 0x74, 0x18, 0x08, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x72, 0x65, 0x63, 0x6c, 0x61, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x72, 0x65, 0x63,
	0x6c, 0x6f, 0x6e, 0x67, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x72, 0x65, 0x63, 0x6c,
	0x6f, 0x6e, 0x67, 0x12, 0x12, 0x0a, 0x04, 0x79, 0x65, 0x61, 0x72, 0x18, 0x0a, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x79, 0x65, 0x61, 0x72, 0x22, 0x5f, 0x0a, 0x14, 0x4d, 0x65, 0x74, 0x65, 0x6f,
	0x72, 0x69, 0x74, 0x65, 0x4c, 0x61, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x4c, 0x69, 0x73, 0x74, 0x12,
	0x47, 0x0a, 0x10, 0x6d, 0x65, 0x74, 0x65, 0x6f, 0x72, 0x69, 0x74, 0x65, 0x4c, 0x61, 0x6e, 0x64,
	0x69, 0x6e, 0x67, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x6d, 0x65, 0x74, 0x65,
	0x6f, 0x72, 0x69, 0x74, 0x65, 0x2e, 0x4d, 0x65, 0x74, 0x65, 0x6f, 0x72, 0x69, 0x74, 0x65, 0x4c,
	0x61, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x52, 0x10, 0x6d, 0x65, 0x74, 0x65, 0x6f, 0x72, 0x69, 0x74,
	0x65, 0x4c, 0x61, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x32, 0x65, 0x0a, 0x18, 0x4d, 0x65, 0x74, 0x65,
	0x6f, 0x72, 0x69, 0x74, 0x65, 0x4c, 0x61, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x73, 0x53, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x12, 0x49, 0x0a, 0x0c, 0x47, 0x65, 0x74, 0x4d, 0x65, 0x74, 0x65, 0x6f,
	0x72, 0x69, 0x74, 0x65, 0x12, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x1f, 0x2e, 0x6d,
	0x65, 0x74, 0x65, 0x6f, 0x72, 0x69, 0x74, 0x65, 0x2e, 0x4d, 0x65, 0x74, 0x65, 0x6f, 0x72, 0x69,
	0x74, 0x65, 0x4c, 0x61, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x4c, 0x69, 0x73, 0x74, 0x22, 0x00, 0x42,
	0x28, 0x5a, 0x26, 0x79, 0x75, 0x64, 0x68, 0x69, 0x73, 0x74, 0x69, 0x72, 0x61, 0x2e, 0x64, 0x65,
	0x76, 0x2f, 0x64, 0x65, 0x6d, 0x6f, 0x2f, 0x6d, 0x65, 0x74, 0x65, 0x6f, 0x72, 0x69, 0x74, 0x65,
	0x2f, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x61, 0x70, 0x69, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_meteorite_landing_service_proto_rawDescOnce sync.Once
	file_meteorite_landing_service_proto_rawDescData = file_meteorite_landing_service_proto_rawDesc
)

func file_meteorite_landing_service_proto_rawDescGZIP() []byte {
	file_meteorite_landing_service_proto_rawDescOnce.Do(func() {
		file_meteorite_landing_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_meteorite_landing_service_proto_rawDescData)
	})
	return file_meteorite_landing_service_proto_rawDescData
}

var file_meteorite_landing_service_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_meteorite_landing_service_proto_goTypes = []interface{}{
	(*GeoLocation)(nil),          // 0: meteorite.GeoLocation
	(*MeteoriteLanding)(nil),     // 1: meteorite.MeteoriteLanding
	(*MeteoriteLandingList)(nil), // 2: meteorite.MeteoriteLandingList
	(*empty.Empty)(nil),          // 3: google.protobuf.Empty
}
var file_meteorite_landing_service_proto_depIdxs = []int32{
	0, // 0: meteorite.MeteoriteLanding.geolocation:type_name -> meteorite.GeoLocation
	1, // 1: meteorite.MeteoriteLandingList.meteoriteLanding:type_name -> meteorite.MeteoriteLanding
	3, // 2: meteorite.MeteoriteLandingsService.GetMeteorite:input_type -> google.protobuf.Empty
	2, // 3: meteorite.MeteoriteLandingsService.GetMeteorite:output_type -> meteorite.MeteoriteLandingList
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_meteorite_landing_service_proto_init() }
func file_meteorite_landing_service_proto_init() {
	if File_meteorite_landing_service_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_meteorite_landing_service_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GeoLocation); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_meteorite_landing_service_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MeteoriteLanding); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_meteorite_landing_service_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MeteoriteLandingList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_meteorite_landing_service_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_meteorite_landing_service_proto_goTypes,
		DependencyIndexes: file_meteorite_landing_service_proto_depIdxs,
		MessageInfos:      file_meteorite_landing_service_proto_msgTypes,
	}.Build()
	File_meteorite_landing_service_proto = out.File
	file_meteorite_landing_service_proto_rawDesc = nil
	file_meteorite_landing_service_proto_goTypes = nil
	file_meteorite_landing_service_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// MeteoriteLandingsServiceClient is the client API for MeteoriteLandingsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MeteoriteLandingsServiceClient interface {
	GetMeteorite(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*MeteoriteLandingList, error)
}

type meteoriteLandingsServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMeteoriteLandingsServiceClient(cc grpc.ClientConnInterface) MeteoriteLandingsServiceClient {
	return &meteoriteLandingsServiceClient{cc}
}

func (c *meteoriteLandingsServiceClient) GetMeteorite(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*MeteoriteLandingList, error) {
	out := new(MeteoriteLandingList)
	err := c.cc.Invoke(ctx, "/meteorite.MeteoriteLandingsService/GetMeteorite", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MeteoriteLandingsServiceServer is the server API for MeteoriteLandingsService service.
type MeteoriteLandingsServiceServer interface {
	GetMeteorite(context.Context, *empty.Empty) (*MeteoriteLandingList, error)
}

// UnimplementedMeteoriteLandingsServiceServer can be embedded to have forward compatible implementations.
type UnimplementedMeteoriteLandingsServiceServer struct {
}

func (*UnimplementedMeteoriteLandingsServiceServer) GetMeteorite(context.Context, *empty.Empty) (*MeteoriteLandingList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMeteorite not implemented")
}

func RegisterMeteoriteLandingsServiceServer(s *grpc.Server, srv MeteoriteLandingsServiceServer) {
	s.RegisterService(&_MeteoriteLandingsService_serviceDesc, srv)
}

func _MeteoriteLandingsService_GetMeteorite_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MeteoriteLandingsServiceServer).GetMeteorite(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/meteorite.MeteoriteLandingsService/GetMeteorite",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MeteoriteLandingsServiceServer).GetMeteorite(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

var _MeteoriteLandingsService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "meteorite.MeteoriteLandingsService",
	HandlerType: (*MeteoriteLandingsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetMeteorite",
			Handler:    _MeteoriteLandingsService_GetMeteorite_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "meteorite-landing-service.proto",
}
